apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: staging
    spec:
      containers:
      - name: nginx
        image: mrityunjaybhagat/k8s-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
